//! CLI subcommands.

pub mod affected;
pub mod cache;
pub mod common;
pub mod complete;
pub mod completion;
pub mod configurations;
pub mod doctor;
pub mod doctor_builders;
pub mod doctor_cache;
pub mod doctor_determinate;
pub mod doctor_env;
pub mod envrc;
pub mod explain;
pub mod fmt;
pub mod graph;
pub mod inspect;
pub mod list;
pub mod manpage;
pub mod nix_op;
pub mod plan;
pub mod run;
pub mod select;
pub mod task;
pub mod views;
pub mod watch;
