//! Shared Nix emission for `nxr migrate`.

use std::fmt::Write as _;

/// One migrated recipe/task mapped to an nxr app (and optional task deps).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MigratedEntry {
    pub name: String,
    pub description: String,
    pub script: String,
    pub depends_on: Vec<String>,
}

/// Render a `perSystem` fragment with `nxr.apps` and optional `nxr.tasks`.
#[must_use]
pub fn render_per_system_fragment(
    source_label: &str,
    limitations: &[&str],
    entries: &[MigratedEntry],
) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "# Generated by nxr migrate ({source_label}). Review before committing."
    )
    .expect("string write");
    writeln!(
        out,
        "# Best-effort mapping — recipes are never executed by migrate."
    )
    .expect("string write");
    if !limitations.is_empty() {
        writeln!(out, "# Limitations:").expect("string write");
        for item in limitations {
            writeln!(out, "# - {item}").expect("string write");
        }
    }
    writeln!(out).expect("string write");
    writeln!(out, "nxr.apps = {{").expect("string write");
    for entry in entries {
        writeln!(out, "  {} = {{", nix_attr_name(&entry.name)).expect("string write");
        writeln!(
            out,
            "    description = \"{}\";",
            escape_nix_string(&entry.description)
        )
        .expect("string write");
        writeln!(out, "    script = ''").expect("string write");
        for line in entry.script.lines() {
            writeln!(out, "      {line}").expect("string write");
        }
        writeln!(out, "    '';").expect("string write");
        writeln!(out, "  }};").expect("string write");
    }
    writeln!(out, "}};").expect("string write");

    let has_task_deps = entries.iter().any(|entry| !entry.depends_on.is_empty());
    if has_task_deps {
        writeln!(out).expect("string write");
        writeln!(out, "nxr.tasks = {{").expect("string write");
        for entry in entries {
            writeln!(out, "  {} = {{", nix_attr_name(&entry.name)).expect("string write");
            writeln!(out, "    app = \"{}\";", escape_nix_string(&entry.name))
                .expect("string write");
            if !entry.depends_on.is_empty() {
                let deps = entry
                    .depends_on
                    .iter()
                    .map(|dep| format!("\"{}\"", escape_nix_string(dep)))
                    .collect::<Vec<_>>()
                    .join(" ");
                writeln!(out, "    dependsOn = [ {deps} ];").expect("string write");
            }
            writeln!(out, "  }};").expect("string write");
        }
        writeln!(out, "}};").expect("string write");
    }

    out
}

fn nix_attr_name(name: &str) -> String {
    if name
        .chars()
        .all(|ch| ch.is_ascii_alphanumeric() || ch == '-' || ch == '_')
        && !name.is_empty()
        && name
            .chars()
            .next()
            .is_some_and(|ch| ch.is_ascii_alphabetic() || ch == '_')
    {
        name.to_owned()
    } else {
        format!("\"{}\"", escape_nix_string(name))
    }
}

fn escape_nix_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::{MigratedEntry, render_per_system_fragment};

    #[test]
    fn renders_apps_and_task_dependencies() {
        let fragment = render_per_system_fragment(
            "justfile",
            &["shebang recipes are copied verbatim"],
            &[MigratedEntry {
                name: "test".to_owned(),
                description: "Migrated from justfile recipe `test`".to_owned(),
                script: "cargo test".to_owned(),
                depends_on: vec!["build".to_owned()],
            }],
        );
        assert!(fragment.contains("nxr.apps = {"));
        assert!(fragment.contains("nxr.tasks = {"));
        assert!(fragment.contains("dependsOn = [ \"build\" ];"));
    }
}
