# Home Manager module: programs.nxr
#
# Permanent install, shell completion, optional direnv integration, and a
# user config.toml for defaults. Never stores secret values.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib) mkIf mkOption mkEnableOption types;

  cfg = config.programs.nxr;

  settingsToml =
    let
      jobs = toString cfg.settings.defaultJobs;
      shellMode = cfg.settings.shellMode;
      output = cfg.settings.output;
      color = cfg.settings.color;
    in
    ''
      # Generated by programs.nxr (Home Manager). Do not store secrets here.
      default_jobs = ${jobs}
      shell_mode = "${shellMode}"
      output = "${output}"
      color = "${color}"
    '';

  completionHook =
    shell:
    let
      share = "${cfg.package}/share";
    in
    {
      bash = ''
        # nxr Home Manager shell integration
        export XDG_DATA_DIRS="${share}''${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
        if [ -f "${share}/bash-completion/completions/nxr" ]; then
          # shellcheck disable=SC1091
          . "${share}/bash-completion/completions/nxr"
        fi
      '';
      zsh = ''
        # nxr Home Manager shell integration
        export XDG_DATA_DIRS="${share}''${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
        fpath=("${share}/zsh/site-functions" $fpath)
        if [ -f "${share}/zsh/site-functions/_nxr" ]; then
          autoload -U _nxr
        fi
      '';
      fish = ''
        # nxr Home Manager shell integration
        set -gx XDG_DATA_DIRS "${share}" $XDG_DATA_DIRS
        if test -f "${share}/fish/vendor_completions.d/nxr.fish"
          source "${share}/fish/vendor_completions.d/nxr.fish"
        end
      '';
    }
    .${shell};
in
{
  options.programs.nxr = {
    enable = mkEnableOption "nxr flake app runner";

    package = mkOption {
      type = types.package;
      example = lib.literalExpression "inputs.nxr.packages.\${pkgs.system}.nxr";
      description = ''
        nxr package to install. Typical value:
        `inputs.nxr.packages.''${pkgs.system}.nxr`.
      '';
    };

    settings = {
      defaultJobs = mkOption {
        type = types.ints.positive;
        default = 1;
        description = "Default `-j` / `--jobs` for task execution.";
      };
      shellMode = mkOption {
        type = types.enum [
          "smart"
          "always"
          "never"
        ];
        default = "smart";
        description = "Default `--shell-mode`.";
      };
      output = mkOption {
        type = types.enum [
          "live"
          "grouped"
          "failures"
          "summary"
          "raw"
        ];
        default = "live";
        description = "Default `--output` mode for tasks.";
      };
      color = mkOption {
        type = types.enum [
          "auto"
          "always"
          "never"
        ];
        default = "auto";
        description = "Default `--color` policy.";
      };
    };

    shellIntegration = {
      bash = mkOption {
        type = types.bool;
        default = true;
        description = "Install Bash completion and session hooks.";
      };
      zsh = mkOption {
        type = types.bool;
        default = true;
        description = "Install Zsh completion and session hooks.";
      };
      fish = mkOption {
        type = types.bool;
        default = true;
        description = "Install Fish completion and session hooks.";
      };
    };

    direnvIntegration = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = "Enable Home Manager direnv with optional nix-direnv.";
      };
      nixDirenv = mkOption {
        type = types.bool;
        default = true;
        description = "Enable programs.direnv.nix-direnv when direnvIntegration.enable.";
      };
    };

    # Stub surfaces for 3.0 — references/paths only; never secret values.
    trustedProjects = mkOption {
      type = types.attrsOf (
        types.submodule {
          options.allowedSecrets = mkOption {
            type = types.listOf types.str;
            default = [ ];
            description = "Logical secret references allowed for this project (3.0).";
          };
        }
      );
      default = { };
      description = "Project trust allow-lists (references only; unused until schema v2).";
    };

    secretBindings = mkOption {
      type = types.attrsOf (
        types.submodule {
          options = {
            provider = mkOption {
              type = types.str;
              description = "Secret provider id (for example sops-nix).";
            };
            path = mkOption {
              type = types.str;
              description = "Runtime filesystem path to the secret file (never the value).";
            };
          };
        }
      );
      default = { };
      description = "Logical secret ref → provider path bindings (3.0; never store values).";
    };
  };

  config = mkIf cfg.enable {
    home.packages = [ cfg.package ];

    xdg.configFile."nxr/config.toml".text = settingsToml;

    programs.bash.initExtra = mkIf cfg.shellIntegration.bash (completionHook "bash");
    programs.zsh.initExtra = mkIf cfg.shellIntegration.zsh (completionHook "zsh");
    programs.fish.interactiveShellInit = mkIf cfg.shellIntegration.fish (completionHook "fish");

    programs.direnv = mkIf cfg.direnvIntegration.enable {
      enable = true;
      nix-direnv.enable = cfg.direnvIntegration.nixDirenv;
    };
  };
}
