# Home Manager module: programs.nxr
#
# Permanent install, shell completion, optional direnv integration, and a
# user config.toml for defaults. Never stores secret values.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib) mkIf mkOption mkEnableOption types;

  cfg = config.programs.nxr;

  settingsToml =
    let
      jobs = toString cfg.settings.defaultJobs;
      shellMode = cfg.settings.shellMode;
      output = cfg.settings.output;
      color = cfg.settings.color;
    in
    ''
      # Generated by programs.nxr (Home Manager). Do not store secrets here.
      default_jobs = ${jobs}
      shell_mode = "${shellMode}"
      output = "${output}"
      color = "${color}"
    '';

  completionHook =
    shell:
    let
      share = "${cfg.package}/share";
    in
    {
      bash = ''
        # nxr Home Manager shell integration
        export XDG_DATA_DIRS="${share}''${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
        if [ -f "${share}/bash-completion/completions/nxr" ]; then
          # shellcheck disable=SC1091
          . "${share}/bash-completion/completions/nxr"
        fi
      '';
      zsh = ''
        # nxr Home Manager shell integration
        export XDG_DATA_DIRS="${share}''${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
        fpath=("${share}/zsh/site-functions" $fpath)
        if [ -f "${share}/zsh/site-functions/_nxr" ]; then
          autoload -U _nxr
        fi
      '';
      fish = ''
        # nxr Home Manager shell integration
        set -gx XDG_DATA_DIRS "${share}" $XDG_DATA_DIRS
        if test -f "${share}/fish/vendor_completions.d/nxr.fish"
          source "${share}/fish/vendor_completions.d/nxr.fish"
        end
      '';
    }
    .${shell};
in
{
  options.programs.nxr = {
    enable = mkEnableOption "nxr flake app runner";

    package = mkOption {
      type = types.package;
      example = lib.literalExpression "inputs.nxr.packages.\${pkgs.system}.nxr";
      description = ''
        nxr package to install. Typical value:
        `inputs.nxr.packages.''${pkgs.system}.nxr`.
      '';
    };

    settings = {
      defaultJobs = mkOption {
        type = types.ints.positive;
        default = 1;
        description = "Default `-j` / `--jobs` for task execution.";
      };
      shellMode = mkOption {
        type = types.enum [
          "smart"
          "always"
          "never"
        ];
        default = "smart";
        description = "Default `--shell-mode`.";
      };
      output = mkOption {
        type = types.enum [
          "live"
          "grouped"
          "failures"
          "summary"
          "raw"
        ];
        default = "live";
        description = "Default `--output` mode for tasks.";
      };
      color = mkOption {
        type = types.enum [
          "auto"
          "always"
          "never"
        ];
        default = "auto";
        description = "Default `--color` policy.";
      };
    };

    shellIntegration = {
      bash = mkOption {
        type = types.bool;
        default = true;
        description = "Install Bash completion and session hooks.";
      };
      zsh = mkOption {
        type = types.bool;
        default = true;
        description = "Install Zsh completion and session hooks.";
      };
      fish = mkOption {
        type = types.bool;
        default = true;
        description = "Install Fish completion and session hooks.";
      };
    };

    direnvIntegration = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = "Enable Home Manager direnv with optional nix-direnv.";
      };
      nixDirenv = mkOption {
        type = types.bool;
        default = true;
        description = "Enable programs.direnv.nix-direnv when direnvIntegration.enable.";
      };
    };

    # Stub surfaces — references/paths only; never secret values.
    # Not yet wired into trust/config generation (still unused).
    trustedProjects = mkOption {
      type = types.attrsOf (
        types.submodule {
          options.allowedSecrets = mkOption {
            type = types.listOf types.str;
            default = [ ];
            description = "Logical secret references allowed for this project (stub; unused).";
          };
        }
      );
      default = { };
      description = "Project trust allow-lists (references only; stub — unused).";
    };

    secretBindings = mkOption {
      type = types.attrsOf (
        types.submodule {
          options = {
            provider = mkOption {
              type = types.str;
              description = "Secret provider id (for example sops-nix).";
            };
            path = mkOption {
              type = types.str;
              description = "Runtime filesystem path to the secret file (never the value).";
            };
          };
        }
      );
      default = { };
      description = "Logical secret ref → provider path bindings (stub — unused; never store values).";
    };
  };

  options.services.nxrd = {
    enable = mkEnableOption "optional local nxr cache/coordination daemon (nxrd)";

    package = mkOption {
      type = types.package;
      description = "Package providing `nxr` (`nxr daemon start --foreground`).";
    };

    evalWorker = mkOption {
      type = types.bool;
      default = false;
      description = "Set NXR_EVAL_WORKER=1 (experimental; Determinate-eligible hosts only).";
    };

    logBroker = mkOption {
      type = types.bool;
      default = true;
      description = "Leave process log broker enabled (set NXR_LOG_BROKER=off when false).";
    };
  };

  config = lib.mkMerge [
    (mkIf cfg.enable {
      home.packages = [ cfg.package ];

      # When the CLI is enabled, default the daemon package to the same binary.
      services.nxrd.package = lib.mkDefault cfg.package;

      xdg.configFile."nxr/config.toml".text = settingsToml;

      programs.bash.initExtra = mkIf cfg.shellIntegration.bash (completionHook "bash");
      programs.zsh.initExtra = mkIf cfg.shellIntegration.zsh (completionHook "zsh");
      programs.fish.interactiveShellInit = mkIf cfg.shellIntegration.fish (completionHook "fish");

      programs.direnv = mkIf cfg.direnvIntegration.enable {
        enable = true;
        nix-direnv.enable = cfg.direnvIntegration.nixDirenv;
      };
    })

    (mkIf config.services.nxrd.enable (
      let
        nxrdPkg = config.services.nxrd.package;
        nxrdEnv =
          lib.optionalAttrs config.services.nxrd.evalWorker {
            NXR_EVAL_WORKER = "1";
          }
          // lib.optionalAttrs (!config.services.nxrd.logBroker) {
            NXR_LOG_BROKER = "off";
          };
      in
      {
        systemd.user.services.nxrd = lib.mkIf pkgs.stdenv.isLinux {
          Unit = {
            Description = "nxr local cache/coordination daemon (nxrd)";
            Documentation = "https://github.com/willmortimer/nxr";
          };
          Service = {
            ExecStart = "${nxrdPkg}/bin/nxr daemon start --foreground";
            Restart = "on-failure";
            Environment = lib.mapAttrsToList (k: v: "${k}=${v}") nxrdEnv;
          };
          Install.WantedBy = [ "default.target" ];
        };

        launchd.agents.nxrd = lib.mkIf pkgs.stdenv.isDarwin {
          enable = true;
          config = {
            Label = "dev.nxr.nxrd";
            ProgramArguments = [
              "${nxrdPkg}/bin/nxr"
              "daemon"
              "start"
              "--foreground"
            ];
            RunAtLoad = true;
            KeepAlive = true;
            EnvironmentVariables = nxrdEnv;
          };
        };
      }
    ))
  ];
}
